// Code generated by command: go run asmgen.go -vecUint64 -out ../../math/vec/asm_vec_amd64.s -stubs ../../math/vec/asm_vec_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func addUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·addUint64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU (AX)(DI*8), Y0
	VMOVDQU (CX)(DI*8), Y1
	VPADDQ  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (AX)(DI*8), SI
	MOVQ (CX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (DX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET

// func subUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·subUint64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU (AX)(DI*8), Y0
	VMOVDQU (CX)(DI*8), Y1
	VPSUBQ  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(DI*8)
	ADDQ    $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (AX)(DI*8), SI
	MOVQ (CX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (DX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET

// func scalarMulUint64AssignAVX2(v0 []uint64, c uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·scalarMulUint64AssignAVX2(SB), NOSPLIT, $0-56
	MOVQ         v0_base+0(FP), AX
	MOVQ         vOut_base+32(FP), CX
	MOVQ         vOut_len+40(FP), DX
	MOVQ         DX, BX
	SHRQ         $0x02, BX
	SHLQ         $0x02, BX
	VPBROADCASTQ c+24(FP), Y0
	VPSHUFD      $0xb1, Y0, Y1
	XORQ         SI, SI
	JMP          loop_end

loop_body:
	VMOVDQU  (AX)(SI*8), Y2
	VPMULLD  Y2, Y1, Y3
	VPSRLQ   $0x20, Y3, Y4
	VPADDQ   Y3, Y4, Y3
	VPSLLQ   $0x20, Y3, Y3
	VPMULUDQ Y2, Y0, Y2
	VPADDQ   Y2, Y3, Y2
	VMOVDQU  Y2, (CX)(SI*8)
	ADDQ     $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	MOVQ c+24(FP), BX
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (AX)(SI*8), DI
	IMULQ BX, DI
	MOVQ  DI, (CX)(SI*8)
	ADDQ  $0x01, SI

leftover_loop_end:
	CMPQ SI, DX
	JL   leftover_loop_body
	RET

// func scalarMulAddUint64AssignAVX2(v0 []uint64, c uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·scalarMulAddUint64AssignAVX2(SB), NOSPLIT, $0-56
	MOVQ         v0_base+0(FP), AX
	MOVQ         vOut_base+32(FP), CX
	MOVQ         vOut_len+40(FP), DX
	MOVQ         DX, BX
	SHRQ         $0x02, BX
	SHLQ         $0x02, BX
	VPBROADCASTQ c+24(FP), Y0
	VPSHUFD      $0xb1, Y0, Y1
	XORQ         SI, SI
	JMP          loop_end

loop_body:
	VMOVDQU  (AX)(SI*8), Y2
	VMOVDQU  (CX)(SI*8), Y3
	VPMULLD  Y2, Y1, Y4
	VPSRLQ   $0x20, Y4, Y5
	VPADDQ   Y4, Y5, Y4
	VPSLLQ   $0x20, Y4, Y4
	VPMULUDQ Y2, Y0, Y2
	VPADDQ   Y2, Y4, Y2
	VPADDQ   Y2, Y3, Y3
	VMOVDQU  Y3, (CX)(SI*8)
	ADDQ     $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	MOVQ c+24(FP), BX
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (AX)(SI*8), DI
	MOVQ  (CX)(SI*8), R8
	IMULQ BX, DI
	ADDQ  DI, R8
	MOVQ  R8, (CX)(SI*8)
	ADDQ  $0x01, SI

leftover_loop_end:
	CMPQ SI, DX
	JL   leftover_loop_body
	RET

// func scalarMulSubUint64AssignAVX2(v0 []uint64, c uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·scalarMulSubUint64AssignAVX2(SB), NOSPLIT, $0-56
	MOVQ         v0_base+0(FP), AX
	MOVQ         vOut_base+32(FP), CX
	MOVQ         vOut_len+40(FP), DX
	MOVQ         DX, BX
	SHRQ         $0x02, BX
	SHLQ         $0x02, BX
	VPBROADCASTQ c+24(FP), Y0
	VPSHUFD      $0xb1, Y0, Y1
	XORQ         SI, SI
	JMP          loop_end

loop_body:
	VMOVDQU  (AX)(SI*8), Y2
	VMOVDQU  (CX)(SI*8), Y3
	VPMULLD  Y2, Y1, Y4
	VPSRLQ   $0x20, Y4, Y5
	VPADDQ   Y4, Y5, Y4
	VPSLLQ   $0x20, Y4, Y4
	VPMULUDQ Y2, Y0, Y2
	VPADDQ   Y2, Y4, Y2
	VPSUBQ   Y2, Y3, Y3
	VMOVDQU  Y3, (CX)(SI*8)
	ADDQ     $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	MOVQ c+24(FP), BX
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (AX)(SI*8), DI
	MOVQ  (CX)(SI*8), R8
	IMULQ BX, DI
	SUBQ  DI, R8
	MOVQ  R8, (CX)(SI*8)
	ADDQ  $0x01, SI

leftover_loop_end:
	CMPQ SI, DX
	JL   leftover_loop_body
	RET

// func elementWiseMulUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·elementWiseMulUint64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU  (AX)(DI*8), Y0
	VMOVDQU  (CX)(DI*8), Y1
	VPSHUFD  $0xb1, Y0, Y2
	VPMULLD  Y1, Y2, Y2
	VPSRLQ   $0x20, Y2, Y3
	VPADDQ   Y2, Y3, Y2
	VPSLLQ   $0x20, Y2, Y2
	VPMULUDQ Y1, Y0, Y0
	VPADDQ   Y0, Y2, Y0
	VMOVDQU  Y0, (DX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (AX)(DI*8), SI
	MOVQ  (CX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  SI, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET

// func elementWiseMulAddUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·elementWiseMulAddUint64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU  (AX)(DI*8), Y0
	VMOVDQU  (CX)(DI*8), Y1
	VMOVDQU  (DX)(DI*8), Y2
	VPSHUFD  $0xb1, Y0, Y3
	VPMULLD  Y1, Y3, Y3
	VPSRLQ   $0x20, Y3, Y4
	VPADDQ   Y3, Y4, Y3
	VPSLLQ   $0x20, Y3, Y3
	VPMULUDQ Y1, Y0, Y0
	VPADDQ   Y0, Y3, Y1
	VPADDQ   Y1, Y2, Y2
	VMOVDQU  Y2, (DX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (AX)(DI*8), SI
	MOVQ  (CX)(DI*8), R8
	MOVQ  (DX)(DI*8), R9
	IMULQ R8, SI
	ADDQ  SI, R9
	MOVQ  R9, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET

// func elementWiseMulSubUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
// Requires: AVX, AVX2
TEXT ·elementWiseMulSubUint64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	SHLQ $0x02, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU  (AX)(DI*8), Y0
	VMOVDQU  (CX)(DI*8), Y1
	VMOVDQU  (DX)(DI*8), Y2
	VPSHUFD  $0xb1, Y0, Y3
	VPMULLD  Y1, Y3, Y3
	VPSRLQ   $0x20, Y3, Y4
	VPADDQ   Y3, Y4, Y3
	VPSLLQ   $0x20, Y3, Y3
	VPMULUDQ Y1, Y0, Y0
	VPADDQ   Y0, Y3, Y1
	VPSUBQ   Y1, Y2, Y2
	VMOVDQU  Y2, (DX)(DI*8)
	ADDQ     $0x04, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (AX)(DI*8), SI
	MOVQ  (CX)(DI*8), R8
	MOVQ  (DX)(DI*8), R9
	IMULQ R8, SI
	SUBQ  SI, R9
	MOVQ  R9, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, BX
	JL   leftover_loop_body
	RET
