// Code generated by command: go run asmgen.go -vecUint64 -out ../../math/vec/asm_vec_amd64.s -stubs ../../math/vec/asm_vec_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func subUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func scalarMulUint64AssignAVX2(v0 []uint64, c uint64, vOut []uint64)

//go:noescape
func scalarMulAddUint64AssignAVX2(v0 []uint64, c uint64, vOut []uint64)

//go:noescape
func scalarMulSubUint64AssignAVX2(v0 []uint64, c uint64, vOut []uint64)

//go:noescape
func elementWiseMulUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func elementWiseMulAddUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)

//go:noescape
func elementWiseMulSubUint64AssignAVX2(v0 []uint64, v1 []uint64, vOut []uint64)
