// Code generated by command: go run asmgen.go -convert -out ../../math/poly/asm_convert_amd64.s -stubs ../../math/poly/asm_convert_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

DATA EXP2_52<>+0(SB)/8, $(4503599627370496.0)
GLOBL EXP2_52<>(SB), RODATA|NOPTR, $8

DATA EXP2_84_63<>+0(SB)/8, $(19342822337206104000000000.0)
GLOBL EXP2_84_63<>(SB), RODATA|NOPTR, $8

DATA EXP2_84_63_52<>+0(SB)/8, $(19342822341709703000000000.0)
GLOBL EXP2_84_63_52<>(SB), RODATA|NOPTR, $8

DATA EXP2_64<>+0(SB)/8, $(18446744073709552000.0)
GLOBL EXP2_64<>(SB), RODATA|NOPTR, $8

DATA EXP2_64_INV<>+0(SB)/8, $(0.00000000000000000005421010862427522)
GLOBL EXP2_64_INV<>(SB), RODATA|NOPTR, $8

DATA MANT_MASK<>+0(SB)/8, $0x000fffffffffffff
GLOBL MANT_MASK<>(SB), RODATA|NOPTR, $8

DATA BIT_MANT_MASK<>+0(SB)/8, $0x0010000000000000
GLOBL BIT_MANT_MASK<>(SB), RODATA|NOPTR, $8

DATA EXP_MASK<>+0(SB)/8, $0x00000000000007ff
GLOBL EXP_MASK<>(SB), RODATA|NOPTR, $8

DATA EXP_SHIFT<>+0(SB)/8, $0x000000000000043e
GLOBL EXP_SHIFT<>(SB), RODATA|NOPTR, $8

// func convertUint64ToFloat64AssignAVX2(p []uint64, fpOut []float64)
// Requires: AVX, AVX2
TEXT ·convertUint64ToFloat64AssignAVX2(SB), NOSPLIT, $0-48
	MOVQ         p_base+0(FP), AX
	MOVQ         fpOut_base+24(FP), CX
	MOVQ         fpOut_len+32(FP), DX
	VBROADCASTSD EXP2_52<>+0(SB), Y0
	VBROADCASTSD EXP2_84_63<>+0(SB), Y1
	VBROADCASTSD EXP2_84_63_52<>+0(SB), Y2
	XORQ         BX, BX
	JMP          loop_end

loop_body:
	VMOVDQU  (AX)(BX*8), Y3
	VPBLENDD $0x55, Y3, Y0, Y4
	VPSRLQ   $0x20, Y3, Y3
	VPXOR    Y1, Y3, Y3
	VSUBPD   Y2, Y3, Y3
	VADDPD   Y3, Y4, Y3
	VMOVUPD  Y3, (CX)(BX*8)
	ADDQ     $0x04, BX

loop_end:
	CMPQ BX, DX
	JL   loop_body
	RET

// func convertFloat64ToUint64AssignAVX2(fp []float64, pOut []uint64)
// Requires: AVX, AVX2
TEXT ·convertFloat64ToUint64AssignAVX2(SB), NOSPLIT, $0-48
	MOVQ         fp_base+0(FP), AX
	MOVQ         pOut_base+24(FP), CX
	MOVQ         fp_len+8(FP), DX
	VBROADCASTSD MANT_MASK<>+0(SB), Y0
	VBROADCASTSD BIT_MANT_MASK<>+0(SB), Y1
	VBROADCASTSD EXP_MASK<>+0(SB), Y2
	VBROADCASTSD EXP_SHIFT<>+0(SB), Y3
	VPXOR        Y4, Y4, Y4
	XORQ         BX, BX
	JMP          loop_end

loop_body:
	VMOVUPD   (AX)(BX*8), Y5
	VANDPD    Y0, Y5, Y6
	VORPD     Y1, Y6, Y6
	VPSRLQ    $0x34, Y5, Y7
	VANDPD    Y2, Y7, Y7
	VPSRLQ    $0x3f, Y5, Y5
	VPSUBQ    Y5, Y4, Y5
	VPSLLQ    $0x0b, Y6, Y6
	VPSUBQ    Y7, Y3, Y7
	VPSRLVQ   Y7, Y6, Y6
	VPSUBQ    Y6, Y4, Y7
	VPBLENDVB Y5, Y7, Y6, Y5
	VMOVDQU   Y5, (CX)(BX*8)
	ADDQ      $0x04, BX

loop_end:
	CMPQ BX, DX
	JL   loop_body
	RET

// func floatModQInPlaceAVX2(fp []float64)
// Requires: AVX
TEXT ·floatModQInPlaceAVX2(SB), NOSPLIT, $0-24
	MOVQ         fp_base+0(FP), AX
	MOVQ         fp_len+8(FP), CX
	VBROADCASTSD EXP2_64<>+0(SB), Y0
	VBROADCASTSD EXP2_64_INV<>+0(SB), Y1
	XORQ         DX, DX
	JMP          loop_end

loop_body:
	VMOVUPD  (AX)(DX*8), Y2
	VMULPD   Y1, Y2, Y2
	VROUNDPD $0x00, Y2, Y3
	VSUBPD   Y3, Y2, Y2
	VMULPD   Y0, Y2, Y2
	VROUNDPD $0x00, Y2, Y2
	VMOVUPD  Y2, (AX)(DX*8)
	ADDQ     $0x04, DX

loop_end:
	CMPQ DX, CX
	JL   loop_body
	RET
