// Code generated by command: go run asmgen.go -rfft -out ../../math/poly/asm_rfft_amd64.s -stubs ../../math/poly/asm_rfft_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func rfftInPlaceAVX2(coeffs []float64, tw []complex128)

//go:noescape
func rifftInPlaceAVX2(coeffs []float64, tw []complex128)

//go:noescape
func convolveAssignAVX2(fp0 []float64, fp1 []float64, fpOut []float64)
