// Code generated by command: go run asmgen.go -convert -out ../../math/poly/asm_convert_amd64.s -stubs ../../math/poly/asm_convert_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func convertUint64ToFloat64AssignAVX2(p []uint64, fpOut []float64)

//go:noescape
func convertFloat64ToUint64AssignAVX2(fp []float64, pOut []uint64)

//go:noescape
func floatModQInPlaceAVX2(fp []float64)
