// Code generated by command: go run asmgen.go -vecFloat64 -out ../../math/poly/asm_vec_float64_amd64.s -stubs ../../math/poly/asm_vec_float64_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

package poly

//go:noescape
func addFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func subFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func negFloat64AssignAVX2(v0 []float64, vOut []float64)

//go:noescape
func scalarMulFloat64AssignAVX2(v0 []float64, c float64, vOut []float64)

//go:noescape
func scalarMulAddFloat64AssignAVX2(v0 []float64, c float64, vOut []float64)

//go:noescape
func scalarMulSubFloat64AssignAVX2(v0 []float64, c float64, vOut []float64)

//go:noescape
func elementWiseMulFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func elementWiseMulAddFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)

//go:noescape
func elementWiseMulSubFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)
