// Code generated by command: go run asmgen.go -vecFloat64 -out ../../math/poly/asm_vec_float64_amd64.s -stubs ../../math/poly/asm_vec_float64_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func addFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)
// Requires: AVX
TEXT ·addFloat64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	XORQ SI, SI
	JMP  loop_end

loop_body:
	VMOVDQU (AX)(SI*8), Y0
	VMOVDQU (CX)(SI*8), Y1
	VADDPD  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(SI*8)
	ADDQ    $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	RET

// func subFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)
// Requires: AVX
TEXT ·subFloat64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	XORQ SI, SI
	JMP  loop_end

loop_body:
	VMOVDQU (AX)(SI*8), Y0
	VMOVDQU (CX)(SI*8), Y1
	VSUBPD  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(SI*8)
	ADDQ    $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	RET

// func negFloat64AssignAVX2(v0 []float64, vOut []float64)
// Requires: AVX, AVX2
TEXT ·negFloat64AssignAVX2(SB), NOSPLIT, $0-48
	MOVQ  v0_base+0(FP), AX
	MOVQ  vOut_base+24(FP), CX
	MOVQ  vOut_len+32(FP), DX
	VPXOR Y0, Y0, Y0
	XORQ  BX, BX
	JMP   loop_end

loop_body:
	VMOVDQU (AX)(BX*8), Y1
	VSUBPD  Y1, Y0, Y1
	VMOVDQU Y1, (CX)(BX*8)
	ADDQ    $0x04, BX

loop_end:
	CMPQ BX, DX
	JL   loop_body
	RET

// func scalarMulFloat64AssignAVX2(v0 []float64, c float64, vOut []float64)
// Requires: AVX
TEXT ·scalarMulFloat64AssignAVX2(SB), NOSPLIT, $0-56
	MOVQ         v0_base+0(FP), AX
	MOVQ         vOut_base+32(FP), CX
	MOVQ         vOut_len+40(FP), DX
	VBROADCASTSD c+24(FP), Y0
	XORQ         BX, BX
	JMP          loop_end

loop_body:
	VMOVDQU (AX)(BX*8), Y1
	VMULPD  Y1, Y0, Y1
	VMOVDQU Y1, (CX)(BX*8)
	ADDQ    $0x04, BX

loop_end:
	CMPQ BX, DX
	JL   loop_body
	RET

// func scalarMulAddFloat64AssignAVX2(v0 []float64, c float64, vOut []float64)
// Requires: AVX, FMA3
TEXT ·scalarMulAddFloat64AssignAVX2(SB), NOSPLIT, $0-56
	MOVQ         v0_base+0(FP), AX
	MOVQ         vOut_base+32(FP), CX
	MOVQ         vOut_len+40(FP), DX
	VBROADCASTSD c+24(FP), Y0
	XORQ         BX, BX
	JMP          loop_end

loop_body:
	VMOVDQU     (AX)(BX*8), Y1
	VMOVDQU     (CX)(BX*8), Y2
	VFMADD231PD Y1, Y0, Y2
	VMOVDQU     Y2, (CX)(BX*8)
	ADDQ        $0x04, BX

loop_end:
	CMPQ BX, DX
	JL   loop_body
	RET

// func scalarMulSubFloat64AssignAVX2(v0 []float64, c float64, vOut []float64)
// Requires: AVX, FMA3
TEXT ·scalarMulSubFloat64AssignAVX2(SB), NOSPLIT, $0-56
	MOVQ         v0_base+0(FP), AX
	MOVQ         vOut_base+32(FP), CX
	MOVQ         vOut_len+40(FP), DX
	VBROADCASTSD c+24(FP), Y0
	XORQ         BX, BX
	JMP          loop_end

loop_body:
	VMOVDQU      (AX)(BX*8), Y1
	VMOVDQU      (CX)(BX*8), Y2
	VFNMADD231PD Y1, Y0, Y2
	VMOVDQU      Y2, (CX)(BX*8)
	ADDQ         $0x04, BX

loop_end:
	CMPQ BX, DX
	JL   loop_body
	RET

// func elementWiseMulFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)
// Requires: AVX
TEXT ·elementWiseMulFloat64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	XORQ SI, SI
	JMP  loop_end

loop_body:
	VMOVDQU (AX)(SI*8), Y0
	VMOVDQU (CX)(SI*8), Y1
	VMULPD  Y1, Y0, Y0
	VMOVDQU Y0, (DX)(SI*8)
	ADDQ    $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	RET

// func elementWiseMulAddFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)
// Requires: AVX, FMA3
TEXT ·elementWiseMulAddFloat64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	XORQ SI, SI
	JMP  loop_end

loop_body:
	VMOVDQU     (AX)(SI*8), Y0
	VMOVDQU     (CX)(SI*8), Y1
	VMOVDQU     (DX)(SI*8), Y2
	VFMADD231PD Y1, Y0, Y2
	VMOVDQU     Y2, (DX)(SI*8)
	ADDQ        $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	RET

// func elementWiseMulSubFloat64AssignAVX2(v0 []float64, v1 []float64, vOut []float64)
// Requires: AVX, FMA3
TEXT ·elementWiseMulSubFloat64AssignAVX2(SB), NOSPLIT, $0-72
	MOVQ v0_base+0(FP), AX
	MOVQ v1_base+24(FP), CX
	MOVQ vOut_base+48(FP), DX
	MOVQ vOut_len+56(FP), BX
	XORQ SI, SI
	JMP  loop_end

loop_body:
	VMOVDQU      (AX)(SI*8), Y0
	VMOVDQU      (CX)(SI*8), Y1
	VMOVDQU      (DX)(SI*8), Y2
	VFNMADD231PD Y1, Y0, Y2
	VMOVDQU      Y2, (DX)(SI*8)
	ADDQ         $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	RET
