// Code generated by command: go run asmgen.go -rfft -out ../../math/poly/asm_rfft_amd64.s -stubs ../../math/poly/asm_rfft_stub_amd64.go -pkg=poly. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func rfftInPlaceAVX2(coeffs []float64, tw []complex128)
// Requires: AVX, FMA3, SSE2
TEXT ·rfftInPlaceAVX2(SB), NOSPLIT, $0-48
	MOVQ coeffs_base+0(FP), AX
	MOVQ tw_base+24(FP), CX
	MOVQ coeffs_len+8(FP), DX
	XORQ BX, BX
	MOVQ DX, SI
	SHRQ $0x04, SI
	MOVQ DX, DI
	SHRQ $0x03, DI
	MOVQ DX, R8
	SHRQ $0x02, R8
	ADDQ $0x02, BX
	XORQ R9, R9
	MOVQ R9, R10
	ADDQ R8, R10
	MOVQ R10, R11
	ADDQ R8, R11
	MOVQ R11, R12
	ADDQ R8, R12
	JMP  first_loop_end

first_loop_body:
	VMOVUPD (AX)(R9*8), Y0
	VMOVUPD (AX)(R10*8), Y1
	VMOVUPD (AX)(R11*8), Y2
	VMOVUPD (AX)(R12*8), Y3
	VADDPD  Y2, Y0, Y4
	VADDPD  Y3, Y1, Y5
	VSUBPD  Y2, Y0, Y0
	VSUBPD  Y1, Y3, Y1
	VMOVUPD Y4, (AX)(R9*8)
	VMOVUPD Y5, (AX)(R10*8)
	VMOVUPD Y0, (AX)(R11*8)
	VMOVUPD Y1, (AX)(R12*8)
	ADDQ    $0x04, R9
	ADDQ    $0x04, R10
	ADDQ    $0x04, R11
	ADDQ    $0x04, R12

first_loop_end:
	CMPQ R9, R8
	JL   first_loop_body
	SHRQ $0x02, DX
	MOVQ $0x0000000000000002, R9
	JMP  m_loop_end

m_loop_body:
	SHRQ $0x01, DX
	ADDQ $0x02, BX
	XORQ R10, R10
	MOVQ R10, R11
	ADDQ DX, R11
	MOVQ R11, R12
	ADDQ DX, R12
	MOVQ R12, R13
	ADDQ DX, R13
	JMP  j_first_loop_end

j_first_loop_body:
	VMOVUPD (AX)(R10*8), Y0
	VMOVUPD (AX)(R11*8), Y1
	VMOVUPD (AX)(R12*8), Y2
	VMOVUPD (AX)(R13*8), Y3
	VADDPD  Y2, Y0, Y4
	VADDPD  Y3, Y1, Y5
	VSUBPD  Y2, Y0, Y0
	VSUBPD  Y1, Y3, Y1
	VMOVUPD Y4, (AX)(R10*8)
	VMOVUPD Y5, (AX)(R11*8)
	VMOVUPD Y0, (AX)(R12*8)
	VMOVUPD Y1, (AX)(R13*8)
	ADDQ    $0x04, R10
	ADDQ    $0x04, R11
	ADDQ    $0x04, R12
	ADDQ    $0x04, R13

j_first_loop_end:
	CMPQ R10, DX
	JL   j_first_loop_body
	MOVQ $0x0000000000000001, R10
	JMP  i_loop_end

i_loop_body:
	VBROADCASTSD (CX)(BX*8), Y0
	VBROADCASTSD 8(CX)(BX*8), Y1
	ADDQ         $0x02, BX
	MOVQ         DX, R11
	IMULQ        R10, R11
	SHLQ         $0x02, R11
	MOVQ         R11, R12
	ADDQ         DX, R12
	MOVQ         R11, R13
	ADDQ         DX, R13
	MOVQ         R13, R14
	ADDQ         DX, R14
	MOVQ         R14, R15
	ADDQ         DX, R15
	JMP          j_loop_end

j_loop_body:
	VMOVUPD      (AX)(R11*8), Y2
	VMOVUPD      (AX)(R13*8), Y4
	VMOVUPD      (AX)(R14*8), Y3
	VMOVUPD      (AX)(R15*8), Y5
	VMULPD       Y4, Y0, Y6
	VFNMADD231PD Y5, Y1, Y6
	VMULPD       Y5, Y0, Y5
	VFMADD231PD  Y4, Y1, Y5
	VADDPD       Y6, Y2, Y4
	VADDPD       Y5, Y3, Y7
	VSUBPD       Y6, Y2, Y2
	VSUBPD       Y3, Y5, Y3
	VMOVUPD      Y4, (AX)(R11*8)
	VMOVUPD      Y7, (AX)(R13*8)
	VMOVUPD      Y2, (AX)(R14*8)
	VMOVUPD      Y3, (AX)(R15*8)
	ADDQ         $0x04, R11
	ADDQ         $0x04, R13
	ADDQ         $0x04, R14
	ADDQ         $0x04, R15

j_loop_end:
	CMPQ R11, R12
	JL   j_loop_body
	ADDQ $0x01, R10

i_loop_end:
	CMPQ R10, R9
	JL   i_loop_body
	SHLQ $0x01, R9

m_loop_end:
	CMPQ    R9, SI
	JLE     m_loop_body
	VPXOR   X0, X0, X0
	ADDQ    $0x02, BX
	VMOVUPD (AX), X1
	VMOVUPD 16(AX), X2
	VMOVUPD 32(AX), X3
	VMOVUPD 48(AX), X4
	VADDPD  X3, X1, X5
	VADDPD  X4, X2, X6
	VSUBPD  X3, X1, X1
	VSUBPD  X2, X4, X2
	VMOVUPD X5, (AX)
	VMOVUPD X6, 16(AX)
	VMOVUPD X1, 32(AX)
	VMOVUPD X2, 48(AX)
	MOVQ    $0x0000000000000001, DX
	JMP     last_loop_2_end

last_loop_2_body:
	VMOVUPD      (CX)(BX*8), X1
	VSHUFPD      $0x03, X1, X1, X2
	VSHUFPD      $0x00, X1, X1, X1
	ADDQ         $0x02, BX
	MOVQ         DX, SI
	SHLQ         $0x03, SI
	VMOVUPD      (AX)(SI*8), X3
	VMOVUPD      16(AX)(SI*8), X5
	VMOVUPD      32(AX)(SI*8), X4
	VMOVUPD      48(AX)(SI*8), X6
	VMULPD       X5, X1, X7
	VFNMADD231PD X6, X2, X7
	VMULPD       X6, X1, X1
	VFMADD231PD  X5, X2, X1
	VADDPD       X7, X3, X2
	VADDPD       X1, X4, X5
	VSUBPD       X7, X3, X3
	VSUBPD       X4, X1, X1
	VMOVUPD      X2, (AX)(SI*8)
	VMOVUPD      X5, 16(AX)(SI*8)
	VMOVUPD      X3, 32(AX)(SI*8)
	VMOVUPD      X1, 48(AX)(SI*8)
	ADDQ         $0x01, DX

last_loop_2_end:
	CMPQ      DX, DI
	JL        last_loop_2_body
	ADDQ      $0x02, BX
	VMOVUPD   (AX), X1
	VMOVUPD   16(AX), X2
	VADDPD    X2, X1, X3
	VSUBPD    X2, X1, X1
	VADDSUBPD X1, X0, X1
	VSUBPD    X1, X0, X1
	VMOVUPD   X3, (AX)
	VMOVUPD   X1, 16(AX)
	MOVQ      $0x0000000000000001, DX
	JMP       last_loop_1_end

last_loop_1_body:
	VMOVUPD        (CX)(BX*8), X1
	VSHUFPD        $0x03, X1, X1, X2
	VSHUFPD        $0x00, X1, X1, X1
	ADDQ           $0x02, BX
	MOVQ           DX, SI
	SHLQ           $0x02, SI
	VMOVUPD        (AX)(SI*8), X3
	VMOVUPD        16(AX)(SI*8), X4
	VSHUFPD        $0x00, X4, X3, X5
	VSHUFPD        $0x03, X4, X3, X6
	VSHUFPD        $0x03, X3, X4, X3
	VMULPD         X3, X2, X2
	VFMADDSUB231PD X6, X1, X2
	VADDPD         X2, X5, X1
	VSUBPD         X2, X5, X2
	VADDSUBPD      X2, X0, X2
	VSUBPD         X2, X0, X2
	VMOVUPD        X1, (AX)(SI*8)
	VMOVUPD        X2, 16(AX)(SI*8)
	ADDQ           $0x01, DX

last_loop_1_end:
	CMPQ   DX, R8
	JL     last_loop_1_body
	MOVQ   (AX), X0
	MOVQ   8(AX), X1
	MOVUPD X0, X2
	ADDPD  X1, X2
	MOVUPD X0, X0
	SUBPD  X1, X0
	MOVQ   X2, (AX)
	MOVQ   X0, 8(AX)
	RET

// func rifftInPlaceAVX2(coeffs []float64, tw []complex128)
// Requires: AVX, AVX2, FMA3, SSE2
TEXT ·rifftInPlaceAVX2(SB), NOSPLIT, $0-48
	MOVQ      coeffs_base+0(FP), AX
	MOVQ      tw_base+24(FP), CX
	MOVQ      coeffs_len+8(FP), DX
	XORQ      BX, BX
	MOVQ      DX, SI
	SHRQ      $0x04, SI
	MOVQ      DX, DI
	SHRQ      $0x03, DI
	SHRQ      $0x02, DX
	MOVQ      $0x3fe0000000000000, R8
	MOVQ      R8, X0
	MOVQ      (AX), X1
	MOVQ      8(AX), X2
	MOVUPD    X1, X3
	ADDPD     X2, X3
	MULPD     X0, X3
	MOVUPD    X1, X1
	SUBPD     X2, X1
	MULPD     X0, X1
	MOVQ      X3, (AX)
	MOVQ      X1, 8(AX)
	VPXOR     X0, X0, X0
	ADDQ      $0x02, BX
	VMOVUPD   (AX), X1
	VMOVUPD   16(AX), X2
	VADDSUBPD X2, X0, X2
	VSUBPD    X2, X0, X2
	VADDPD    X2, X1, X3
	VSUBPD    X2, X1, X1
	VMOVUPD   X3, (AX)
	VMOVUPD   X1, 16(AX)
	MOVQ      $0x0000000000000001, R8
	JMP       first_loop_end

first_loop_body:
	VMOVUPD        (CX)(BX*8), X1
	VSHUFPD        $0x03, X1, X1, X2
	VSHUFPD        $0x00, X1, X1, X1
	ADDQ           $0x02, BX
	MOVQ           R8, R9
	SHLQ           $0x02, R9
	VMOVUPD        (AX)(R9*8), X3
	VMOVUPD        16(AX)(R9*8), X4
	VADDSUBPD      X4, X0, X4
	VSUBPD         X4, X0, X4
	VADDPD         X4, X3, X5
	VSUBPD         X4, X3, X3
	VSHUFPD        $0x01, X3, X3, X4
	VMULPD         X4, X2, X2
	VFMADDSUB231PD X3, X1, X2
	VSHUFPD        $0x00, X2, X5, X1
	VSHUFPD        $0x03, X2, X5, X2
	VMOVUPD        X1, (AX)(R9*8)
	VMOVUPD        X2, 16(AX)(R9*8)
	ADDQ           $0x01, R8

first_loop_end:
	CMPQ    R8, DX
	JL      first_loop_body
	ADDQ    $0x02, BX
	VMOVUPD (AX), X1
	VMOVUPD 16(AX), X2
	VMOVUPD 32(AX), X3
	VMOVUPD 48(AX), X4
	VSUBPD  X4, X0, X4
	VADDPD  X3, X1, X5
	VADDPD  X4, X2, X6
	VSUBPD  X3, X1, X1
	VSUBPD  X4, X2, X2
	VMOVUPD X5, (AX)
	VMOVUPD X6, 16(AX)
	VMOVUPD X1, 32(AX)
	VMOVUPD X2, 48(AX)
	MOVQ    $0x0000000000000001, R8
	JMP     first_loop_2_end

first_loop_2_body:
	VMOVUPD      (CX)(BX*8), X1
	VSHUFPD      $0x03, X1, X1, X2
	VSHUFPD      $0x00, X1, X1, X1
	ADDQ         $0x02, BX
	MOVQ         R8, R9
	SHLQ         $0x03, R9
	VMOVUPD      (AX)(R9*8), X3
	VMOVUPD      16(AX)(R9*8), X4
	VMOVUPD      32(AX)(R9*8), X5
	VMOVUPD      48(AX)(R9*8), X6
	VSUBPD       X6, X0, X6
	VADDPD       X5, X3, X7
	VADDPD       X6, X4, X8
	VSUBPD       X5, X3, X3
	VSUBPD       X6, X4, X4
	VMULPD       X3, X1, X5
	VFNMADD231PD X4, X2, X5
	VMULPD       X4, X1, X1
	VFMADD231PD  X3, X2, X1
	VMOVUPD      X7, (AX)(R9*8)
	VMOVUPD      X5, 16(AX)(R9*8)
	VMOVUPD      X8, 32(AX)(R9*8)
	VMOVUPD      X1, 48(AX)(R9*8)
	ADDQ         $0x01, R8

first_loop_2_end:
	CMPQ  R8, DI
	JL    first_loop_2_body
	VPXOR Y0, Y0, Y0
	MOVQ  $0x0000000000000004, DI
	JMP   m_loop_end

m_loop_body:
	ADDQ $0x02, BX
	XORQ R8, R8
	MOVQ R8, R9
	ADDQ DI, R9
	MOVQ R9, R10
	ADDQ DI, R10
	MOVQ R10, R11
	ADDQ DI, R11
	JMP  j_first_loop_end

j_first_loop_body:
	VMOVUPD (AX)(R8*8), Y1
	VMOVUPD (AX)(R9*8), Y2
	VMOVUPD (AX)(R10*8), Y3
	VMOVUPD (AX)(R11*8), Y4
	VSUBPD  Y4, Y0, Y4
	VADDPD  Y3, Y1, Y5
	VADDPD  Y4, Y2, Y6
	VSUBPD  Y3, Y1, Y1
	VSUBPD  Y4, Y2, Y2
	VMOVUPD Y5, (AX)(R8*8)
	VMOVUPD Y6, (AX)(R9*8)
	VMOVUPD Y1, (AX)(R10*8)
	VMOVUPD Y2, (AX)(R11*8)
	ADDQ    $0x04, R8
	ADDQ    $0x04, R9
	ADDQ    $0x04, R10
	ADDQ    $0x04, R11

j_first_loop_end:
	CMPQ R8, DI
	JL   j_first_loop_body
	MOVQ $0x0000000000000001, R8
	JMP  i_loop_end

i_loop_body:
	VBROADCASTSD (CX)(BX*8), Y1
	VBROADCASTSD 8(CX)(BX*8), Y2
	ADDQ         $0x02, BX
	MOVQ         DI, R9
	IMULQ        R8, R9
	SHLQ         $0x02, R9
	MOVQ         R9, R10
	ADDQ         DI, R10
	MOVQ         R9, R11
	ADDQ         DI, R11
	MOVQ         R11, R12
	ADDQ         DI, R12
	MOVQ         R12, R13
	ADDQ         DI, R13
	JMP          j_loop_end

j_loop_body:
	VMOVUPD      (AX)(R9*8), Y3
	VMOVUPD      (AX)(R11*8), Y4
	VMOVUPD      (AX)(R12*8), Y5
	VMOVUPD      (AX)(R13*8), Y6
	VSUBPD       Y6, Y0, Y6
	VADDPD       Y5, Y3, Y7
	VADDPD       Y6, Y4, Y8
	VSUBPD       Y5, Y3, Y3
	VSUBPD       Y6, Y4, Y4
	VMULPD       Y3, Y1, Y5
	VFNMADD231PD Y4, Y2, Y5
	VMULPD       Y4, Y1, Y4
	VFMADD231PD  Y3, Y2, Y4
	VMOVUPD      Y7, (AX)(R9*8)
	VMOVUPD      Y5, (AX)(R11*8)
	VMOVUPD      Y8, (AX)(R12*8)
	VMOVUPD      Y4, (AX)(R13*8)
	ADDQ         $0x04, R9
	ADDQ         $0x04, R11
	ADDQ         $0x04, R12
	ADDQ         $0x04, R13

j_loop_end:
	CMPQ R9, R10
	JL   j_loop_body
	ADDQ $0x01, R8

i_loop_end:
	CMPQ R8, SI
	JL   i_loop_body
	SHRQ $0x01, SI
	SHLQ $0x01, DI

m_loop_end:
	CMPQ SI, $0x02
	JGE  m_loop_body
	ADDQ $0x02, BX
	XORQ CX, CX
	MOVQ CX, BX
	ADDQ DX, BX
	MOVQ BX, SI
	ADDQ DX, SI
	MOVQ SI, DI
	ADDQ DX, DI
	JMP  last_loop_end

last_loop_body:
	VMOVUPD (AX)(CX*8), Y1
	VMOVUPD (AX)(BX*8), Y2
	VMOVUPD (AX)(SI*8), Y3
	VMOVUPD (AX)(DI*8), Y4
	VSUBPD  Y4, Y0, Y4
	VADDPD  Y3, Y1, Y5
	VADDPD  Y4, Y2, Y6
	VSUBPD  Y3, Y1, Y1
	VSUBPD  Y4, Y2, Y2
	VMOVUPD Y5, (AX)(CX*8)
	VMOVUPD Y6, (AX)(BX*8)
	VMOVUPD Y1, (AX)(SI*8)
	VMOVUPD Y2, (AX)(DI*8)
	ADDQ    $0x04, CX
	ADDQ    $0x04, BX
	ADDQ    $0x04, SI
	ADDQ    $0x04, DI

last_loop_end:
	CMPQ CX, DX
	JL   last_loop_body
	RET

// func convolveAssignAVX2(fp0 []float64, fp1 []float64, fpOut []float64)
// Requires: AVX, FMA3
TEXT ·convolveAssignAVX2(SB), NOSPLIT, $0-72
	MOVQ           fp0_base+0(FP), AX
	MOVQ           fp1_base+24(FP), CX
	MOVQ           fpOut_base+48(FP), DX
	MOVQ           fpOut_len+56(FP), BX
	VMOVUPD        (AX), X0
	VMOVUPD        (CX), X1
	VMULPD         X0, X1, X0
	VMOVUPD        X0, (DX)
	VMOVUPD        16(AX), X0
	VMOVUPD        16(CX), X1
	VSHUFPD        $0x00, X0, X0, X2
	VSHUFPD        $0x03, X0, X0, X0
	VSHUFPD        $0x01, X1, X1, X3
	VMULPD         X3, X0, X0
	VFMADDSUB231PD X1, X2, X0
	VMOVUPD        X0, 16(DX)
	MOVQ           $0x0000000000000004, SI
	JMP            loop_end

loop_body:
	VMOVUPD        (AX)(SI*8), Y0
	VMOVUPD        (CX)(SI*8), Y1
	VSHUFPD        $0x00, Y0, Y0, Y2
	VSHUFPD        $0x0f, Y0, Y0, Y0
	VSHUFPD        $0x05, Y1, Y1, Y3
	VMULPD         Y3, Y0, Y0
	VFMADDSUB231PD Y1, Y2, Y0
	VMOVUPD        Y0, (DX)(SI*8)
	ADDQ           $0x04, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	RET
