// Code generated by command: go run asmgen.go -decompose -out ../../carousel/asm_decompose_amd64.s -stubs ../../carousel/asm_decompose_stub_amd64.go -pkg=carousel. DO NOT EDIT.

//go:build amd64 && !purego

package carousel

//go:noescape
func decomposePolyAssignUint64AVX2(p []uint64, base uint64, logBase uint64, logLastBaseQ uint64, decomposedOut [][]uint64)
